2020-09-24 17:43:23,965 - D:\ZYCami_00\Public\Caplictily.py[line:43] - ERROR: No driver
2020-09-24 17:47:49,126 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 17:47:49,126 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 17:47:49,126 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 17:47:49,126 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:01:51,761 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:01:51,761 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:01:51,761 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:01:51,761 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:03:09,915 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:03:09,915 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:03:09,915 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:03:09,915 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:06:31,772 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:06:31,772 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:06:31,772 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:06:31,772 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:08:54,893 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:08:54,893 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:08:54,893 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 18:08:54,893 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:51:47,728 - D:\ZYCami_00\TestCase\test_01.py[line:80] - ERROR: 没有登录
2020-09-24 20:51:47,728 - D:\ZYCami_00\TestCase\test_01.py[line:80] - ERROR: 没有登录
2020-09-24 20:51:47,728 - D:\ZYCami_00\TestCase\test_01.py[line:80] - ERROR: 没有登录
2020-09-24 20:52:57,017 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:52:57,017 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:52:57,017 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:52:57,017 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:54:24,667 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:54:24,667 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:54:24,667 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:54:24,667 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 20:56:41,573 - D:\ZYCami_00\TestCase\test_01.py[line:81] - ERROR: 没有登录
2020-09-24 20:56:41,573 - D:\ZYCami_00\TestCase\test_01.py[line:81] - ERROR: 没有登录
2020-09-24 20:56:41,573 - D:\ZYCami_00\TestCase\test_01.py[line:81] - ERROR: 没有登录
2020-09-24 21:39:23,651 - D:\ZYCami_00\Public\Caplictily.py[line:43] - ERROR: No driver
2020-09-24 21:39:23,651 - D:\ZYCami_00\Public\Caplictily.py[line:43] - ERROR: No driver
2020-09-24 21:39:23,651 - D:\ZYCami_00\Public\Caplictily.py[line:43] - ERROR: No driver
2020-09-24 21:39:23,653 - D:\ZYCami_00\TestCase\test_01.py[line:82] - INFO: 没有登录
2020-09-24 21:39:23,653 - D:\ZYCami_00\TestCase\test_01.py[line:82] - INFO: 没有登录
2020-09-24 21:39:23,653 - D:\ZYCami_00\TestCase\test_01.py[line:82] - INFO: 没有登录
2020-09-24 21:39:23,654 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 21:39:23,654 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 21:39:23,654 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
2020-09-24 21:39:23,654 - D:\ZYCami_00\Public\Logins.py[line:40] - ERROR: 登录失败
